// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarUploadController from "./avatar_upload_controller"
application.register("avatar-upload", AvatarUploadController)

import GeminiTopicController from "./gemini_topic_controller"
application.register("topic", GeminiTopicController)

import GeminiAnswerController from "./gemini_answer_controller"
application.register("answer", GeminiAnswerController)

import TopicsSearchController from "./topics_search_controller"
application.register("topics-search", TopicsSearchController)

import RankingsController from "./rankings_controller"
application.register("rankings", RankingsController)
