// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarUploadController from "./avatar_upload_controller"
application.register("avatar-upload", AvatarUploadController)

import GeminiController from "./gemini_controller"
application.register("gemini", GeminiController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
